-- SQL Schema for Series-to-Shorts Autonomous YouTube Agent
-- Idempotent script (Safe to run multiple times)

-- 1. Table for tracking video processing state
CREATE TABLE IF NOT EXISTS videos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    url TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'Pending',
    title TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE videos ENABLE ROW LEVEL SECURITY;

-- Drop and recreate policy to avoid "already exists" error
DROP POLICY IF EXISTS "Allow service role full access" ON videos;
CREATE POLICY "Allow service role full access" ON videos 
    FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- 2. Table for system health logs (Vitals)
CREATE TABLE IF NOT EXISTS health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT now(),
    status TEXT NOT NULL,
    disk_usage FLOAT NOT NULL,
    ram_usage FLOAT NOT NULL
);

ALTER TABLE health_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service role full access" ON health_logs;
CREATE POLICY "Allow service role full access" ON health_logs 
    FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- 3. Table for Weekly Analytics
CREATE TABLE IF NOT EXISTS weekly_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT now(),
    views INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    subscribers_gained INTEGER DEFAULT 0
);

ALTER TABLE weekly_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service role full access" ON weekly_stats;
CREATE POLICY "Allow service role full access" ON weekly_stats 
    FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- Functions and Triggers
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql'
SET search_path = public;

DROP TRIGGER IF EXISTS update_videos_updated_at ON videos;
CREATE TRIGGER update_videos_updated_at
    BEFORE UPDATE ON videos
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
