-- SQL Schema for Series-to-Shorts Autonomous YouTube Agent
-- Updated with security hardening (RLS and search_path)

-- 1. Table for tracking video processing state
CREATE TABLE IF NOT EXISTS videos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    url TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'Pending', -- Pending, Processing, Completed, Error
    title TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;

-- Add policies for Service Role (Agent access)
-- Note: Service role bypasses RLS by default, but enabling RLS and adding policies is best practice for defense in depth.
-- If the user wants to access this from a frontend, they would need more granular policies.
CREATE POLICY "Allow service role full access" ON videos 
    FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- 2. Table for system health logs (Vitals)
CREATE TABLE IF NOT EXISTS health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT now(),
    status TEXT NOT NULL, -- Healthy, Warning
    disk_usage FLOAT NOT NULL,
    ram_usage FLOAT NOT NULL
);

ALTER TABLE health_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow service role full access" ON health_logs 
    FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- 3. Table for Weekly Analytics (Optional)
CREATE TABLE IF NOT EXISTS weekly_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT now(),
    views INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    subscribers_gained INTEGER DEFAULT 0
);

ALTER TABLE weekly_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow service role full access" ON weekly_stats 
    FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- Trigger to update 'updated_at' on video status change
-- Hardened with SET search_path to public to prevent search_path attacks
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql'
SET search_path = public;

-- Drop trigger if exists to avoid errors on re-run
DROP TRIGGER IF EXISTS update_videos_updated_at ON videos;

CREATE TRIGGER update_videos_updated_at
    BEFORE UPDATE ON videos
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
