-- SQL Schema for Series-to-Shorts Autonomous YouTube Agent

-- 1. Table for tracking video processing state
CREATE TABLE IF NOT EXISTS videos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    url TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'Pending', -- Pending, Processing, Completed, Error
    title TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Table for system health logs (Vitals)
CREATE TABLE IF NOT EXISTS health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT now(),
    status TEXT NOT NULL, -- Healthy, Warning
    disk_usage FLOAT NOT NULL,
    ram_usage FLOAT NOT NULL
);

-- 3. Table for Weekly Analytics (Optional)
CREATE TABLE IF NOT EXISTS weekly_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT now(),
    views INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    subscribers_gained INTEGER DEFAULT 0
);

-- Trigger to update 'updated_at' on video status change
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_videos_updated_at
    BEFORE UPDATE ON videos
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
